name: Test go-sidekiq
on: [push]


jobs:

  build:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          # Opens tcp port 6379 on the host and service container
          - 6379:6379
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v -timeout 1m ./...
